### ISSUE TITLE
Making code blocks wider?

### ISSUE THREAD

**Issue by marhar** [maolonglong/hugo-simple#11]
Is there an easy way to set the width of code blocks?  I have some 80-column code I would like to display.

Thanks... hugo simple is very nice looking and pleasant to use.

**Comment by maolonglong** [comment]
I'm not very good at front-end and UI design, but I think it would look a bit strange to just make the width of the code block wider. So we need to make the whole content wider:

<img width="1465" alt="image" src="https://github.com/maolonglong/hugo-simple/assets/50797868/9f3144ad-b24d-45a9-87b7-f8147ae2d9c2">

This can be done with custom css (sorry, I haven't documented this part in the repo yet). You can refer to [this example](https://github.com/maolonglong/chensl.me/blob/d79b31d5470be81c375f14a1876865311231689d/layouts/partials/custom_head.html#L6-L7) which shows how to add custom content to the `<head>...</head>`.

Then you can add a css file that looks like this:

```css
/* assets/my_custom.css */
body {
  /* overrides the default grid width of Simple.css */
  grid-template-columns: 1fr min(60rem, 90%) 1fr;
}
```

> Ref: https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-columns
